### ISSUE TITLE
VIDIOC_QBUF: Invalid argument & NoneType Error

### ISSUE THREAD

**Issue by varun9597** [varun9597/FaceRecogProject#1]
Getting this issue along with the following :

`Traceback (most recent call last):
VIDIOC_QBUF: Invalid argument
  File "face_recog.py", line 42, in <module>
VIDIOC_QBUF: Invalid argument
VIDIOC_QBUF: Invalid argument
    frame = imutils.resize(frame, width=500)
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/convenience.py", line 69, in resize
VIDIOC_QBUF: Invalid argument
VIDIOC_QBUF: Invalid argument
    (h, w) = image.shape[:2]
VIDIOC_QBUF: Invalid argument
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by varun9597** [comment]
This probably means that the camera is not able to communicate with OpenCV and OpenCV is receiving empty frames hence not able to resize it.

What solved - Reconnecting the camera solved the issue.

It might also be that the source of your camera has been not specified properly.

Check the following :
`#vs = VideoStream(src=0).start()
#vs = VideoStream(usePiCamera=True).start()`

src = 0 or src=1 could be the solution in some cases.
For raspberry pi you can write - 'vs = VideoStream(usePiCamera=True).start()`'
